# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.3
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format

-   repo: https://github.com/henriquegemignani/jsonschema-to-typeddict
    rev: v1.1.1
    hooks:
    -   id: jsonschema-to-typeddict
        files: caver/schema/schema.json
        args: [ --output-path, caver/schema/types.py, --root-name, CaverData ]
